name: CI

on: [pull_request]

jobs:
  flatpak:
    name: Flatpak (${{ matrix.arch }}, ${{ matrix.repository-name }})
    runs-on: ${{ matrix.runs-on }}

    strategy:
      matrix:
        include:
          - arch: x86_64
            runs-on: ubuntu-latest
            container-image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-49
            repository-name: flathub
            repository-url: https://flathub.org/repo/flathub.flatpakrepo
          - arch: aarch64
            runs-on: ubuntu-24.04-arm
            container-image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-49
            repository-name: flathub
            repository-url: https://flathub.org/repo/flathub.flatpakrepo
          - arch: x86_64
            runs-on: ubuntu-latest
            container-image: ghcr.io/elementary/flatpak-platform/runtime:8.1-x86_64
            repository-name: appcenter
            repository-url: https://flatpak.elementary.io/repo.flatpakrepo
          - arch: aarch64
            runs-on: ubuntu-24.04-arm
            container-image: ghcr.io/elementary/flatpak-platform/runtime:8.1-aarch64
            repository-name: appcenter
            repository-url: https://flatpak.elementary.io/repo.flatpakrepo
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false

    container:
      image: ${{ matrix.container-image }}
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: reco-${{ matrix.repository-name }}.flatpak
          manifest-path: build-aux/${{ matrix.repository-name }}/com.github.ryonakano.reco.Devel.yml
          run-tests: true
          repository-name: ${{ matrix.repository-name }}
          repository-url: ${{ matrix.repository-url }}
          cache-key: "flatpak-builder-${sha256(manifestPath)}-${{ github.sha }}"
          arch: ${{ matrix.arch }}

  lint:
    name: Lint
    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Lint
        run: io.elementary.vala-lint -d .
