name: CI

on: [pull_request]

jobs:
  deploy_flatpak:
    name: Deploy Flatpak
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/elementary/flatpak-platform/runtime:6
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
        with:
          bundle: reco.flatpak
          manifest-path: com.github.ryonakano.reco.yml
          run-tests: true
          repository-name: appcenter
          repository-url: https://flatpak.elementary.io/repo.flatpakrepo
          cache-key: "flatpak-builder-${{ github.sha }}"

  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: valalang/lint
    steps:
    - uses: actions/checkout@v2
    - name: Lint
      run: io.elementary.vala-lint -d .
